# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\facultate\Anul III\Sem I\PIM-P\try cod\try2\interfata.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
from pacient import Ui_PacientWindow
from selectPacient import Ui_SelectWindow
from help import Ui_HelpWindow
from helper import Ui_Dialog

class Ui_MainWindow(object):
    def iesire(self):
        MainWindow.close()

    def new_pacient(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_PacientWindow()
        self.ui.setupUi(self.window,MainWindow)
        self.window.show()
        self.ui.goBack = MainWindow
        MainWindow.hide()

    def selectPacient(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_SelectWindow()
        self.ui.setupUi(self.window,MainWindow)
        self.window.show()
        MainWindow.hide()


    def helpWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_HelpWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        #MainWindow.hide()


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        #MainWindow.resize(800, 589)
        MainWindow.setFixedWidth(800)
        MainWindow.setFixedHeight(589)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(8)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color:rgb(151, 232, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 390, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)

        self.pushButton.clicked.connect(self.new_pacient)                  ###
        #self.pushButton.clicked.connect(self.openHelper)
        self.pushButton.setGeometry(QtCore.QRect(80, 140, 231, 91))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color:black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 240, 231, 91))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        #self.pushButton_2.clicked.connect(self.openHelper)          ######
        self.pushButton_2.clicked.connect(self.selectPacient)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(80, 350, 231, 91))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(15)
        self.pushButton_3.setFont(font)
        self.pushButton_3.clicked.connect(self.helpWindow)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.clicked.connect(self.iesire)
        self.pushButton_4.setGeometry(QtCore.QRect(80, 450, 231, 91))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(15)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 30, 371, 81))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(410, 210, 321, 281))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("D:\\1_university\\Anul III\\PIM_P_bunSper\\resources/1.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 50, 81, 51))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("D:\\1_university\\Anul III\\PIM_P_bunSper\\resources/2.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(560, 40, 81, 71))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("D:\\1_university\\Anul III\\PIM_P_bunSper\\resources/3.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WolfCoat"))
        self.pushButton.setText(_translate("MainWindow", "New Pacient"))
        self.pushButton_2.setText(_translate("MainWindow", "Select Pacient"))
        self.pushButton_3.setText(_translate("MainWindow", "Help"))
        self.pushButton_4.setText(_translate("MainWindow", "Exit"))
        self.label.setText(_translate("MainWindow", "Welcome to WolfCoat"))
        self.actionNew.setText(_translate("MainWindow", "New"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    uii = Ui_MainWindow()
    uii.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())