# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\1_university\Anul III\PIM_P_bunSper\pacient.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from results import Ui_ResultsWindow
from PyQt5 import QtCore, QtGui, QtWidgets

import sqlite3 as sl
import cv2 as cv
from teleradiografie import Ui_TeleradiografieWindow

class Ui_PacientWindow(object):

    def discard(self):
        self.lineEdit.clear()
        self.lineEdit_2.clear()
        self.lineEdit_3.clear()
        if (self.checkBox_2.isChecked()):
            self.checkBox_2.setChecked(False)
        else:
            if (self.checkBox.isChecked()):
                self.checkBox.setChecked(False)

    def savePacient(self):

        con = sl.connect('DataBase.db')
        if (self.checkBox_2.isChecked()):
            g = 'Female'
        else:
            if (self.checkBox.isChecked()):
                g = 'Male'

        sql = 'INSERT INTO Pacient ( LastName,FirstName, Age,Gender,Path) values( ?, ?,?,?,?)'
        data = [
            (self.lineEdit.text(), self.lineEdit_2.text(), self.lineEdit_3.text(), g,self.lineEdit_4.text())
        ]
        with con:
            con.executemany(sql, data)

    def show_radiografie(self):
        con = sl.connect('DataBase.db')
        cursor = con.cursor()

        cursor.execute("SELECT Path  FROM Pacient")
        results = cursor.fetchall()
        for r in results:
            print(r[0])
        cursor.close()
        con.close()
        img = cv.imread(r[0], 0)
        scale_percent = 0  # percent of original size
        smaller_image = cv.resize(img, (1000, 900))
        cv.imshow('image', smaller_image)

    def home(self,main_w,pacient_w):
        main_w.show()
        pacient_w.close()



    def setupUi(self, PacientWindow,MainWindow):
        PacientWindow.setObjectName("PacientWindow")
        #PacientWindow.resize(800, 600)
        PacientWindow.setFixedWidth(800)
        PacientWindow.setFixedHeight(600)
        PacientWindow.setStyleSheet("background-color: rgb(151, 232, 255);")
        self.centralwidget = QtWidgets.QWidget(PacientWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 50, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 240, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 330, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 140, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(170, 30, 261, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    background: white;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(111, 165, 171);\n"
"}\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(170, 120, 261, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"    background: white;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(111, 165, 171);\n"
"}\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(170, 220, 261, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
"    background: white;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(111, 165, 171);\n"
"}\n"
"")
        self.lineEdit_3.setObjectName("lineEdit_3")

        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(360, 350, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(9)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(190, 350, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(10)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)

        self.pushButton.clicked.connect(self.savePacient)

        self.pushButton.setGeometry(QtCore.QRect(520, 30, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)

        self.pushButton_2.clicked.connect(self.discard)

        self.pushButton_2.setGeometry(QtCore.QRect(520, 220, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(170, 430, 261, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("QLineEdit{\n"
"    background: white;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(111, 165, 171);\n"
"}\n"
"")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_4.setText("resources\\")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 440, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.clicked.connect(self.show_radiografie)
        self.pushButton_3.setGeometry(QtCore.QRect(520, 430, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(15)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        PacientWindow.setCentralWidget(self.centralwidget)

        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 0, 31, 28))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
                                        "    background:rgb(151, 232, 255);\n"
                                        "    border: 2px solid rgb(151, 232, 255);\n"
                                        "    border-radius: 0px;\n"
                                        "    color: black;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover{\n"
                                        "    background-color:rgb(206, 164, 196);\n"
                                        "    border: 2px solid rgb(206, 164, 196);\n"
                                        "}")
        self.pushButton_4.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources\\home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(lambda: self.home(MainWindow,PacientWindow))
        PacientWindow.setCentralWidget(self.centralwidget)




        self.retranslateUi(PacientWindow)
        QtCore.QMetaObject.connectSlotsByName(PacientWindow)

    def retranslateUi(self, PacientWindow):
        _translate = QtCore.QCoreApplication.translate
        PacientWindow.setWindowTitle(_translate("MainWindow", "WolfCoat"))
        self.label.setText(_translate("PacientWindow", "Last Name"))
        self.label_2.setText(_translate("PacientWindow", "Age"))
        self.label_3.setText(_translate("PacientWindow", "Gender"))
        self.label_4.setText(_translate("PacientWindow", "First Name"))
        self.checkBox.setText(_translate("PacientWindow", "Male"))
        self.checkBox_2.setText(_translate("PacientWindow", "Female"))
        self.pushButton.setText(_translate("PacientWindow", "Save"))
        self.pushButton_2.setText(_translate("PacientWindow", "Discard"))
        self.label_5.setText(_translate("PacientWindow", "Path"))
        self.pushButton_3.setText(_translate("PacientWindow", "Upload"))
