# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\1_university\Anul III\PIM_P_bunSper\help.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HelpWindow(object):


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(945, 707)
        MainWindow.setFixedWidth(945)
        MainWindow.setFixedHeight(707)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 941, 661))
        self.tabWidget.setStyleSheet("background-color:rgb(151, 232, 255);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.tab)
        self.stackedWidget_2.setGeometry(QtCore.QRect(90, 30, 781, 591))
        self.stackedWidget_2.setStyleSheet("background-color:rgb(151, 232, 255);")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.label_17 = QtWidgets.QLabel(self.page_11)
        self.label_17.setGeometry(QtCore.QRect(340, 30, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.textEdit_9 = QtWidgets.QTextEdit(self.page_11)
        self.textEdit_9.setGeometry(QtCore.QRect(20, 110, 761, 87))
        self.textEdit_9.setReadOnly(True)
        self.textEdit_9.setObjectName("textEdit_9")
        self.label_18 = QtWidgets.QLabel(self.page_11)
        self.label_18.setGeometry(QtCore.QRect(120, 250, 551, 251))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("D:\\1_university\\Anul III\\PIM_P_bunSper\\resources/N.png"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.stackedWidget_2.addWidget(self.page_11)
        self.page_12 = QtWidgets.QWidget()
        self.page_12.setObjectName("page_12")
        self.textEdit_10 = QtWidgets.QTextEdit(self.page_12)
        self.textEdit_10.setGeometry(QtCore.QRect(10, 120, 761, 87))
        self.textEdit_10.setReadOnly(True)
        self.textEdit_10.setObjectName("textEdit_10")
        self.label_19 = QtWidgets.QLabel(self.page_12)
        self.label_19.setGeometry(QtCore.QRect(350, 30, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.page_12)
        self.label_20.setGeometry(QtCore.QRect(120, 250, 571, 251))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("D:\\1_university\\Anul III\\PIM_P_bunSper\\resources/S.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.stackedWidget_2.addWidget(self.page_12)
        self.page_13 = QtWidgets.QWidget()
        self.page_13.setObjectName("page_13")
        self.textEdit_11 = QtWidgets.QTextEdit(self.page_13)
        self.textEdit_11.setGeometry(QtCore.QRect(20, 110, 761, 87))
        self.textEdit_11.setReadOnly(True)
        self.textEdit_11.setObjectName("textEdit_11")
        self.label_21 = QtWidgets.QLabel(self.page_13)
        self.label_21.setGeometry(QtCore.QRect(350, 30, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.page_13)
        self.label_22.setGeometry(QtCore.QRect(100, 250, 571, 271))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("D:\\1_university\\Anul III\\PIM_P_bunSper\\resources/A.png"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.stackedWidget_2.addWidget(self.page_13)
        self.page_14 = QtWidgets.QWidget()
        self.page_14.setObjectName("page_14")
        self.textEdit_12 = QtWidgets.QTextEdit(self.page_14)
        self.textEdit_12.setGeometry(QtCore.QRect(30, 100, 761, 87))
        self.textEdit_12.setReadOnly(True)
        self.textEdit_12.setObjectName("textEdit_12")
        self.label_23 = QtWidgets.QLabel(self.page_14)
        self.label_23.setGeometry(QtCore.QRect(360, 20, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.page_14)
        self.label_24.setGeometry(QtCore.QRect(90, 230, 621, 301))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap("D:\\1_university\\Anul III\\PIM_P_bunSper\\resources/B.png"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.stackedWidget_2.addWidget(self.page_14)
        self.page_15 = QtWidgets.QWidget()
        self.page_15.setObjectName("page_15")
        self.textEdit_13 = QtWidgets.QTextEdit(self.page_15)
        self.textEdit_13.setGeometry(QtCore.QRect(20, 100, 761, 87))
        self.textEdit_13.setReadOnly(True)
        self.textEdit_13.setObjectName("textEdit_13")
        self.label_25 = QtWidgets.QLabel(self.page_15)
        self.label_25.setGeometry(QtCore.QRect(350, 20, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.page_15)
        self.label_26.setGeometry(QtCore.QRect(80, 230, 621, 301))
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap("D:\\1_university\\Anul III\\PIM_P_bunSper\\resources/Pr.png"))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.stackedWidget_2.addWidget(self.page_15)
        self.page_17 = QtWidgets.QWidget()
        self.page_17.setObjectName("page_17")
        self.textEdit_14 = QtWidgets.QTextEdit(self.page_17)
        self.textEdit_14.setGeometry(QtCore.QRect(30, 100, 761, 87))
        self.textEdit_14.setReadOnly(True)
        self.textEdit_14.setObjectName("textEdit_14")
        self.label_27 = QtWidgets.QLabel(self.page_17)
        self.label_27.setGeometry(QtCore.QRect(360, 20, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.page_17)
        self.label_28.setGeometry(QtCore.QRect(90, 230, 621, 301))
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap("D:\\1_university\\Anul III\\PIM_P_bunSper\\resources/gn.png"))
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName("label_28")
        self.stackedWidget_2.addWidget(self.page_17)
        self.page_18 = QtWidgets.QWidget()
        self.page_18.setObjectName("page_18")
        self.label_30 = QtWidgets.QLabel(self.page_18)
        self.label_30.setGeometry(QtCore.QRect(360, 30, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_29 = QtWidgets.QLabel(self.page_18)
        self.label_29.setGeometry(QtCore.QRect(90, 240, 621, 301))
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap("D:\\1_university\\Anul III\\PIM_P_bunSper\\resources/Me.png"))
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName("label_29")
        self.textEdit_15 = QtWidgets.QTextEdit(self.page_18)
        self.textEdit_15.setGeometry(QtCore.QRect(30, 110, 761, 87))
        self.textEdit_15.setReadOnly(True)
        self.textEdit_15.setObjectName("textEdit_15")
        self.stackedWidget_2.addWidget(self.page_18)
        self.page_19 = QtWidgets.QWidget()
        self.page_19.setObjectName("page_19")
        self.textEdit_16 = QtWidgets.QTextEdit(self.page_19)
        self.textEdit_16.setGeometry(QtCore.QRect(20, 110, 761, 87))
        self.textEdit_16.setReadOnly(True)
        self.textEdit_16.setObjectName("textEdit_16")
        self.label_31 = QtWidgets.QLabel(self.page_19)
        self.label_31.setGeometry(QtCore.QRect(80, 240, 621, 301))
        self.label_31.setText("")
        self.label_31.setPixmap(QtGui.QPixmap("D:\\1_university\\Anul III\\PIM_P_bunSper\\resources/go.png"))
        self.label_31.setScaledContents(True)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.page_19)
        self.label_32.setGeometry(QtCore.QRect(350, 30, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.stackedWidget_2.addWidget(self.page_19)
        self.page_16 = QtWidgets.QWidget()
        self.page_16.setObjectName("page_16")
        self.label_33 = QtWidgets.QLabel(self.page_16)
        self.label_33.setGeometry(QtCore.QRect(80, 250, 621, 301))
        self.label_33.setText("")
        self.label_33.setPixmap(QtGui.QPixmap("D:\\1_university\\Anul III\\PIM_P_bunSper\\resources/G.png"))
        self.label_33.setScaledContents(True)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.page_16)
        self.label_34.setGeometry(QtCore.QRect(350, 40, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.textEdit_17 = QtWidgets.QTextEdit(self.page_16)
        self.textEdit_17.setGeometry(QtCore.QRect(20, 120, 761, 87))
        self.textEdit_17.setReadOnly(True)
        self.textEdit_17.setObjectName("textEdit_17")
        self.stackedWidget_2.addWidget(self.page_16)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.textEdit_18 = QtWidgets.QTextEdit(self.page)
        self.textEdit_18.setGeometry(QtCore.QRect(20, 90, 761, 87))
        self.textEdit_18.setReadOnly(True)
        self.textEdit_18.setObjectName("textEdit_18")
        self.label_35 = QtWidgets.QLabel(self.page)
        self.label_35.setGeometry(QtCore.QRect(350, 10, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.page)
        self.label_36.setGeometry(QtCore.QRect(80, 220, 621, 301))
        self.label_36.setText("")
        self.label_36.setPixmap(QtGui.QPixmap("D:\\1_university\\Anul III\\PIM_P_bunSper\\resources/Pn.png"))
        self.label_36.setScaledContents(True)
        self.label_36.setObjectName("label_36")
        self.stackedWidget_2.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.textEdit_19 = QtWidgets.QTextEdit(self.page_2)
        self.textEdit_19.setGeometry(QtCore.QRect(10, 100, 761, 87))
        self.textEdit_19.setReadOnly(True)
        self.textEdit_19.setObjectName("textEdit_19")
        self.label_37 = QtWidgets.QLabel(self.page_2)
        self.label_37.setGeometry(QtCore.QRect(340, 20, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.page_2)
        self.label_38.setGeometry(QtCore.QRect(70, 230, 621, 301))
        self.label_38.setText("")
        self.label_38.setPixmap(QtGui.QPixmap("D:\\1_university\\Anul III\\PIM_P_bunSper\\resources/Sn.png"))
        self.label_38.setScaledContents(True)
        self.label_38.setObjectName("label_38")
        self.stackedWidget_2.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_39 = QtWidgets.QLabel(self.page_3)
        self.label_39.setGeometry(QtCore.QRect(310, 20, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.textEdit_20 = QtWidgets.QTextEdit(self.page_3)
        self.textEdit_20.setGeometry(QtCore.QRect(20, 100, 761, 87))
        self.textEdit_20.setReadOnly(True)
        self.textEdit_20.setObjectName("textEdit_20")
        self.label_40 = QtWidgets.QLabel(self.page_3)
        self.label_40.setGeometry(QtCore.QRect(80, 230, 621, 301))
        self.label_40.setText("")
        self.label_40.setPixmap(QtGui.QPixmap("D:\\1_university\\Anul III\\PIM_P_bunSper\\resources/Ls.png"))
        self.label_40.setScaledContents(True)
        self.label_40.setObjectName("label_40")
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_41 = QtWidgets.QLabel(self.page_4)
        self.label_41.setGeometry(QtCore.QRect(310, 20, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.page_4)
        self.label_42.setGeometry(QtCore.QRect(80, 230, 621, 301))
        self.label_42.setText("")
        self.label_42.setPixmap(QtGui.QPixmap("D:\\1_university\\Anul III\\PIM_P_bunSper\\resources/Li.png"))
        self.label_42.setScaledContents(True)
        self.label_42.setObjectName("label_42")
        self.textEdit_21 = QtWidgets.QTextEdit(self.page_4)
        self.textEdit_21.setGeometry(QtCore.QRect(20, 100, 761, 87))
        self.textEdit_21.setReadOnly(True)
        self.textEdit_21.setObjectName("textEdit_21")
        self.stackedWidget_2.addWidget(self.page_4)

        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 10, 91, 41))
        self.pushButton_2.clicked.connect(lambda: self.stackedWidget_2.setCurrentIndex(self.stackedWidget_2.currentIndex() - 1))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color:black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")

        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.clicked.connect(lambda: self.stackedWidget_2.setCurrentIndex(self.stackedWidget_2.currentIndex() + 1))
        self.pushButton.setGeometry(QtCore.QRect(810, 10, 111, 41))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color:black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.tab_2)
        self.stackedWidget.setGeometry(QtCore.QRect(110, 80, 711, 471))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label = QtWidgets.QLabel(self.page_5)
        self.label.setGeometry(QtCore.QRect(220, 40, 281, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page_5)
        self.label_2.setGeometry(QtCore.QRect(130, 90, 461, 361))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("D:\\1_university\\Anul III\\PIM_P_bunSper\\resources/SNplan.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.label_3 = QtWidgets.QLabel(self.page_6)
        self.label_3.setGeometry(QtCore.QRect(230, 40, 281, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.page_6)
        self.label_4.setGeometry(QtCore.QRect(140, 90, 461, 361))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("D:\\1_university\\Anul III\\PIM_P_bunSper\\resources/PnPog.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.label_5 = QtWidgets.QLabel(self.page_7)
        self.label_5.setGeometry(QtCore.QRect(230, 40, 281, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.page_7)
        self.label_6.setGeometry(QtCore.QRect(140, 90, 461, 361))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("D:\\1_university\\Anul III\\PIM_P_bunSper\\resources/PnPog_buzainferioara.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.page_7)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(810, 10, 111, 41))
        self.pushButton_3.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(self.stackedWidget.currentIndex() + 1))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color:black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(self.stackedWidget.currentIndex() - 1))
        self.pushButton_4.setGeometry(QtCore.QRect(10, 10, 91, 41))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color:black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 945, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_17.setText(_translate("MainWindow", "Nasion (N)"))
        self.textEdit_9.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Punctul cel mai anterior pe sutura fronto-nazala in plan medio-sagital, corespunde radacinii nasului.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Localizare: se trasează conturul corticalei externe a osului frontal, osul nazal şi structura frontonazală. Punctul unde se unesc cele trei reprezintă Nasion</span></p></body></html>"))
        self.textEdit_10.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Centrul geometric al conturului șeii turcești (sella turcica)</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Localizare: şeaua turcească este situată în porţiunea superioară a osului sfenoid fiind mărginită anterior şi posterior de procesele clinoide; se trasează conturul proceselor clinoide şi marginea inferioară a fosei. Centrul geometric al şeii turceşti reprezintă Sella</span></p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "Sella (S)"))
        self.textEdit_11.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Punctul cel mai posterior pe curbura spinei nazale anterioare sub SNA și în fața rădăcinii incisivului central superior. Punctul cel mai posterior pe conturul osos între SNA-Pr.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Este aproximativ la acelaşi nivel cu apexul incisivului central, cu 2 mm anterior</span></p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "Punctul A"))
        self.textEdit_12.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Punctul cel mai posterior pe profilul procesului alveolar mandibular</span></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "Punctul B"))
        self.textEdit_13.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Punctul cel mai inferior şi anterior al procesului alveolar superior în plan medio-sagital.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Localizare : corespunde cu marginea alveolei incisivului central superior la joncţiunea smalţ-cement </span></p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "PROSTHION (Pr)"))
        self.textEdit_14.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Punctul cel mai anterior și inferior al mentonului.</span></p></body></html>"))
        self.label_27.setText(_translate("MainWindow", "GNATHION (Gn)"))
        self.label_30.setText(_translate("MainWindow", "MENTON (Me)"))
        self.textEdit_15.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Punctul cel mai inferior pe simfiza mentonieră.</span></p></body></html>"))
        self.textEdit_16.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">– Punct anatomic, osos, unilateral</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Punctul cel mai posterior, lateral şi inferior pe fața externă a unghiului mandibulei </span></p></body></html>"))
        self.label_32.setText(_translate("MainWindow", "GONION (Go) "))
        self.label_34.setText(_translate("MainWindow", "GLABELLA (G)"))
        self.textEdit_17.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">– Punct cutanat, unilateral </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Cel mai anterior punct al frunții în plan medio-sagital, la nivelul marginii superioare a orbitei </span></p></body></html>"))
        self.textEdit_18.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">– Punct cutanat, unilateral</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">– Cel mai anterior punct al nasului</span></p></body></html>"))
        self.label_35.setText(_translate("MainWindow", "PRONASALE (Pn) "))
        self.textEdit_19.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">– Punct cutanat, unilateral</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">– Corespunde joncțiunii dintre filtrumului buzei superioare și columela în plan medio-sagital</span></p></body></html>"))
        self.label_37.setText(_translate("MainWindow", "SUBNASALE (Sn) "))
        self.label_39.setText(_translate("MainWindow", "LABIALE SUPERIOR (Ls) "))
        self.textEdit_20.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">– Punct cutanat, unilateral</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">– Punctul cel mai anterior al marginii buzei superioare</span></p></body></html>"))
        self.label_41.setText(_translate("MainWindow", "LABIALE INFERIOR (Li)"))
        self.textEdit_21.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">– Punct cutanat, unilateral</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">– Punctul cel mai anterior al marginii inferioare a buzei inferioare</span></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Prev"))
        self.pushButton.setText(_translate("MainWindow", "Next"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Puncte"))
        self.label.setText(_translate("MainWindow", "Planul cranial: S-N (Sella – Nasion) "))
        self.label_3.setText(_translate("MainWindow", "Buza superioară la linia E (Pn-Pog)"))
        self.label_5.setText(_translate("MainWindow", "Buza inferioara la linia E (Pn-Pog)\n"
""))
        self.pushButton_3.setText(_translate("MainWindow", "Next"))
        self.pushButton_4.setText(_translate("MainWindow", "Prev"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Planuri"))
