# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\facultate\Anul III\Sem I\PIM-P\updated\eu_updated\helper.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sqlite3 as sl
from PyQt5 import QtCore, QtGui, QtWidgets
from results import Ui_ResultsWindow
#from selectPacient import Ui_SelectWindow
class Ui_Dialog(object):
    def showResults(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_ResultsWindow()
        self.ui.setupUi(self.window)
        self.window.show()

        con=sl.connect('unghiuri.db')
        cursor = con.cursor()

        print("sters unghiuri")
        cursor.execute("SELECT SNA,SNB,ANB FROM Unghiuri")
        results = cursor.fetchall()
        self.ui.lineEdit_7.setText(str(results[0][0]))
        self.ui.lineEdit_8.setText(str(results[0][1]))
        self.ui.lineEdit_9.setText(str(results[0][2]))
        self.ui.lineEdit_10.setText(str(round(82-results[0][0],2)))
        self.ui.lineEdit_11.setText(str(round(80 - results[0][1], 2)))
        self.ui.lineEdit_12.setText(str(round(abs(4 - results[0][2]), 2)))

        con2 = sl.connect('distante.db')
        cursor2 = con2.cursor()
        cursor2.execute("SELECT isNA,PLS,PLI FROM Distante")
        results2 = cursor2.fetchall()
        self.ui.lineEdit_27.setText(str(round(results2[0][0]/10,3)))
        self.ui.lineEdit_23.setText(str(round(results2[0][1],3)))
        self.ui.lineEdit_29.setText(str(round(results2[0][2],3)))

        self.ui.lineEdit_22.setText(str(round(abs(4 - results2[0][0]/10), 2)))
        self.ui.lineEdit_30.setText(str(round(abs(4 - results2[0][1]), 2)))
        self.ui.lineEdit_16.setText(str(round(abs(3 - results2[0][2]), 2)))

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(589, 158)
        Dialog.setStyleSheet("background-color: rgb(151, 232, 255);")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(140, 70, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QPushButton{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"}\n"
"")
        self.lineEdit.setText("")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(230, 20, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(310, 80, 181, 51))
        self.pushButton.clicked.connect(self.showResults)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background: pink;\n"
"    border: 2px solid rgb(151, 232, 255);\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(206, 164, 196);\n"
"    border: 2px solid rgb(206, 164, 196);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.hide()


        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "PUNCTE"))
        self.pushButton.setText(_translate("Dialog", "Show Results"))